In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

print("Deltagare 1, Andra raden visar värden från imputationen")
imp1_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp1_mean.fit([[np.nan, np.nan, np.nan, np.nan, np.nan], 
              [13504, 13424, 13600, 13600, 13488], 
              [12832, 13488, 13616, 13648, 13648],
              [12928, 12992, 13024, 12064, 12944],
              [12922, 13312, 13376, 13456, 13568]])
X1 = [[12928, 12992, 13024, 12064, 12944], [np.nan, np.nan, np.nan, np.nan, np.nan]]

print("\n",imp1_mean.transform(X1))


print("\nDeltagare 9, Andra raden visar värden från imputationen")
imp9_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp9_mean.fit([[12592, 12992, 13056, 13312, 13216], 
              [13072, 13136, 12880, 12912, 13216], 
              [13104, 12032, 10688, 9536, 9568],
              [np.nan, np.nan, np.nan, np.nan, np.nan],
              [np.nan, np.nan, np.nan, np.nan, np.nan]])
X9 = [[12592, 12992, 13056, 13312, 13216], [np.nan, np.nan, np.nan, np.nan, np.nan]]

print("\n", imp9_mean.transform(X9))


print("\nDeltagare 6, Andra raden visar värden från imputationen")
imp6_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp6_mean.fit([[np.nan, np.nan, np.nan, np.nan, np.nan], 
              [np.nan, np.nan, np.nan, np.nan, np.nan], 
              [np.nan, np.nan, np.nan, np.nan, np.nan],
              [9568, 10400, 10752, 11216, 11456],
              [11776, 12384, 11856, 12304, 12208]])
X6 = [[9568, 10400, 10752, 11216, 11456], [np.nan, np.nan, np.nan, np.nan, np.nan]]

print("\n", imp6_mean.transform(X6))


print("\nDeltagare 7, Andra raden visar värden från imputationen")
imp7_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp7_mean.fit([[13136, 14080, 13504, 13536, 13728], 
              [np.nan, np.nan, np.nan, np.nan, np.nan], 
              [13344, 13328, 13168, 13536, 13232],
              [13728, 14000, 13872, 13472, 13904],
              [14160, 13856, 13504, 13184, 11904]])
X7 = [[13136, 14080, 13504, 13536, 13728], [np.nan, np.nan, np.nan, np.nan, np.nan]]

print("\n", imp7_mean.transform(X7))


print("\nDeltagare 10, Andra raden visar värden från imputationen")

imp10_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp10_mean.fit([[12144, 13568, 13056, 11872, 10176], 
              [np.nan, np.nan, np.nan, np.nan, np.nan], 
              [12048, 13424, 12704, 12144, 11536],
              [np.nan, np.nan, np.nan, np.nan, np.nan],
              [np.nan, np.nan, np.nan, np.nan, np.nan]])
X10 = [[12144, 13568, 13056, 11872, 10176], [np.nan, np.nan, np.nan, np.nan, np.nan]]

print("\n", imp10_mean.transform(X10))

Deltagare 1, Andra raden visar värden från imputationen

 [[12928.  12992.  13024.  12064.  12944. ]
 [13046.5 13304.  13404.  13192.  13412. ]]

Deltagare 9, Andra raden visar värden från imputationen

 [[12592.         12992.         13056.         13312.
  13216.        ]
 [12922.66666667 12720.         12208.         11920.
  12000.        ]]

Deltagare 6, Andra raden visar värden från imputationen

 [[ 9568. 10400. 10752. 11216. 11456.]
 [10672. 11392. 11304. 11760. 11832.]]

Deltagare 7, Andra raden visar värden från imputationen

 [[13136. 14080. 13504. 13536. 13728.]
 [13592. 13816. 13512. 13432. 13192.]]

Deltagare 10, Andra raden visar värden från imputationen

 [[12144. 13568. 13056. 11872. 10176.]
 [12096. 13496. 12880. 12008. 10856.]]
